---
# =============================================================================
# Ansible Galaxy Requirements
# =============================================================================
# Install with: ansible-galaxy install -r requirements.yml
# =============================================================================

collections:
  - name: community.mongodb
    version: ">=1.6.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"
