---
# =============================================================================
# Molecule Test Configuration
# =============================================================================

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: mongodb-ubuntu22
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - mongodb
    docker_networks:
      - name: molecule-mongodb
        ipam_config:
          - subnet: "10.30.0.0/24"
    networks:
      - name: molecule-mongodb
        ipv4_address: "10.30.0.11"

  - name: mongodb-ubuntu22-2
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - mongodb
    networks:
      - name: molecule-mongodb
        ipv4_address: "10.30.0.12"

  - name: mongodb-ubuntu22-3
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - mongodb
    networks:
      - name: molecule-mongodb
        ipv4_address: "10.30.0.13"

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    group_vars:
      mongodb:
        mongodb_version: "7.0"
        mongodb_deployment_mode: "replicaset"
        mongodb_replicaset_name: "rs0"
        mongodb_security_auth_enabled: true
        mongodb_admin_password: "TestPassword123!"
        mongodb_cluster_admin_password: "TestClusterPass123!"
        mongodb_backup_password: "TestBackupPass123!"
        mongodb_monitoring_password: "TestMonitorPass123!"
        mongodb_configure_firewall: false
        mongodb_configure_selinux: false
        mongodb_backup_enabled: false
        mongodb_exporter_enabled: false
        mongodb_replicaset_members:
          - host: "10.30.0.11:27017"
            priority: 2
          - host: "10.30.0.12:27017"
            priority: 1
          - host: "10.30.0.13:27017"
            priority: 1

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
